import type { IconType } from "react-icons";
import {
  MdSearch,
  MdNotifications,
  MdNotificationsActive,
  MdHelpOutline,
  MdSecurity,
  MdChevronRight,
  MdChevronLeft,
  MdLogout,
  MdSettings,
  MdAccountBalanceWallet,
  MdAccountBalance,
  MdLanguage,
  MdAdd,
  MdAddCircle,
  MdEditNote,
  MdArrowForward,
  MdArrowDownward,
  MdAutoAwesome,
  MdTrendingUp,
  MdTrendingDown,
  MdFilterList,
  MdExpandMore,
  MdDownload,
  MdMoreVert,
  MdSavings,
  MdStars,
  MdCalendarToday,
  MdPsychology,
  MdMail,
  MdLock,
  MdLockReset,
  MdPerson,
  MdVerifiedUser,
  MdDashboard,
  MdPayments,
  MdBarChart,
  MdLeaderboard,
  MdAssessment,
  MdShoppingCart,
  MdShoppingBag,
  MdHome,
  MdDirectionsCar,
  MdBolt,
  MdWork,
  MdRestaurant,
  MdSportsEsports,
  MdFitnessCenter,
  MdRouter,
  MdMovie,
  MdVisibility,
  MdVisibilityOff,
  MdClose,
  MdDelete,
  MdAnalytics,
  MdWarning,
  MdEventRepeat,
  MdCommute,
  MdCheckCircle,
  MdCancel,
  MdLightMode,
} from "react-icons/md";

const iconMap: Record<string, IconType> = {
  search: MdSearch,
  notifications: MdNotifications,
  notifications_active: MdNotificationsActive,
  help_outline: MdHelpOutline,
  security: MdSecurity,
  chevron_right: MdChevronRight,
  chevron_left: MdChevronLeft,
  logout: MdLogout,
  settings: MdSettings,
  account_balance_wallet: MdAccountBalanceWallet,
  account_balance: MdAccountBalance,
  language: MdLanguage,
  add: MdAdd,
  add_circle: MdAddCircle,
  edit_note: MdEditNote,
  arrow_forward: MdArrowForward,
  arrow_downward: MdArrowDownward,
  auto_awesome: MdAutoAwesome,
  trending_up: MdTrendingUp,
  trending_down: MdTrendingDown,
  filter_list: MdFilterList,
  expand_more: MdExpandMore,
  download: MdDownload,
  more_vert: MdMoreVert,
  savings: MdSavings,
  stars: MdStars,
  calendar_today: MdCalendarToday,
  psychology: MdPsychology,
  mail: MdMail,
  lock: MdLock,
  lock_reset: MdLockReset,
  person: MdPerson,
  verified_user: MdVerifiedUser,
  dashboard: MdDashboard,
  payments: MdPayments,
  bar_chart: MdBarChart,
  leaderboard: MdLeaderboard,
  assessment: MdAssessment,
  shopping_cart: MdShoppingCart,
  shopping_bag: MdShoppingBag,
  home: MdHome,
  directions_car: MdDirectionsCar,
  bolt: MdBolt,
  work: MdWork,
  restaurant: MdRestaurant,
  sports_esports: MdSportsEsports,
  fitness_center: MdFitnessCenter,
  router: MdRouter,
  movie: MdMovie,
  visibility: MdVisibility,
  visibility_off: MdVisibilityOff,
  close: MdClose,
  delete: MdDelete,
  analytics: MdAnalytics,
  warning: MdWarning,
  event_repeat: MdEventRepeat,
  commute: MdCommute,
  check_circle: MdCheckCircle,
  cancel: MdCancel,
  light_mode: MdLightMode,
};

export function Icon({
  name,
  className = "",
  filled: _filled = false,
}: {
  name: string;
  className?: string;
  filled?: boolean;
}) {
  const IconComponent = iconMap[name];

  if (!IconComponent) {
    return null;
  }

  return <IconComponent className={`icon ${className}`} />;
}
